'use strict';

const { BrowserWindow, session } = require('electron');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

const PARTITION = 'minarrador-pdf';

/**
 * Renders a local HTML file to PDF in a throwaway window.
 *
 * The renderer is deliberately inert: JavaScript is off and every request that
 * is not the file itself is cancelled, so model-authored markup cannot execute
 * or phone home. That keeps the "nothing leaves this machine" promise even
 * though the HTML was generated by a model.
 */
async function htmlToPdf(htmlPath, pdfPath) {
  const ses = session.fromPartition(PARTITION, { cache: false });

  const allowedPrefixes = ['file://', 'data:', 'about:blank', 'devtools://'];
  ses.webRequest.onBeforeRequest((details, callback) => {
    callback({ cancel: !allowedPrefixes.some((p) => details.url.startsWith(p)) });
  });

  const win = new BrowserWindow({
    show: false,
    width: 900,
    height: 1200,
    webPreferences: {
      session: ses,
      javascript: false,
      sandbox: true,
      contextIsolation: true,
      nodeIntegration: false,
      webSecurity: true,
      images: true,
    },
  });

  try {
    await win.loadURL(pathToFileURL(htmlPath).toString());
    // Give layout (web fonts are blocked, so this is just a paint settle) a beat.
    await new Promise((r) => setTimeout(r, 250));

    const data = await win.webContents.printToPDF({
      printBackground: true,
      pageSize: 'Letter',
      margins: { top: 0.5, bottom: 0.5, left: 0.5, right: 0.5 },
      preferCSSPageSize: false,
    });

    fs.mkdirSync(path.dirname(pdfPath), { recursive: true });
    fs.writeFileSync(pdfPath, data);
    return pdfPath;
  } finally {
    if (!win.isDestroyed()) win.destroy();
    ses.webRequest.onBeforeRequest(null);
  }
}

module.exports = { htmlToPdf };
