'use strict';

const { BrowserWindow, session } = require('electron');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

let renderSeq = 0;

/**
 * Renders a local HTML file to PDF in a throwaway window.
 *
 * The renderer is deliberately inert: JavaScript is off and every request that
 * is not the file itself is cancelled, so model-authored markup cannot execute
 * or phone home. That keeps the "nothing leaves this machine" promise even
 * though the HTML was generated by a model.
 *
 * Each render gets its own session partition. Electron keeps a single
 * onBeforeRequest listener per session, so two meetings finishing at once used
 * to share one: the second render replaced the first's filter, and whichever
 * finished first cleared it out from under the other, leaving a model-authored
 * page briefly able to reach the network. Isolating the partition removes the
 * shared state entirely.
 *
 * @param {string} htmlPath source document on disk
 * @param {string} pdfPath destination PDF
 * @returns {Promise<string>} the path written
 */
async function htmlToPdf(htmlPath, pdfPath) {
  const partition = `minarrador-pdf-${process.pid}-${++renderSeq}`;
  const ses = session.fromPartition(partition, { cache: false });

  const allowedPrefixes = ['file://', 'data:', 'about:blank', 'devtools://'];
  ses.webRequest.onBeforeRequest((details, callback) => {
    callback({ cancel: !allowedPrefixes.some((p) => details.url.startsWith(p)) });
  });

  const win = new BrowserWindow({
    show: false,
    width: 900,
    height: 1200,
    webPreferences: {
      session: ses,
      javascript: false,
      sandbox: true,
      contextIsolation: true,
      nodeIntegration: false,
      webSecurity: true,
      images: true,
    },
  });

  try {
    await win.loadURL(pathToFileURL(htmlPath).toString());
    // Give layout (web fonts are blocked, so this is just a paint settle) a beat.
    await new Promise((r) => setTimeout(r, 250));

    const data = await win.webContents.printToPDF({
      printBackground: true,
      pageSize: 'Letter',
      margins: { top: 0.5, bottom: 0.5, left: 0.5, right: 0.5 },
      preferCSSPageSize: false,
    });

    fs.mkdirSync(path.dirname(pdfPath), { recursive: true });
    fs.writeFileSync(pdfPath, data);
    return pdfPath;
  } finally {
    if (!win.isDestroyed()) win.destroy();
    // The partition is single-use; drop its cached state rather than unhooking
    // a filter another render might still be relying on.
    await ses.clearStorageData().catch(() => {});
  }
}

module.exports = { htmlToPdf };
